Add HCC Installation Detector
RadeonOpenCompute/hcc-clang-upgrade pull request #100
Opened 2017-10-26 20:39 UTC by vsytch

This change adds the HccInstallationDetector class. During initialisation it looks for a valid hcc installation and then adds the corresponding compilation and link arguments.

By default it looks in the directory from which hcc was invoked and in the directory in which clang(that's pointed by the invoked hcc) is. To manually specify a hcc installation add `--hcc-path=/path/to/hcc` to your arguments. 

We now always link to `libmcwamp.a` and `libhc_am.so`. To not link to them add `-fno-hcc-bootstrap` to your arguments.

2017-11-02 01:45 UTC, scchan requested changes
A lot of the PSTL tests are failing, could you take a look?  Here's an example:


In file included from /home/scchan/code/hcc/tests/Unit/ParallelSTL/unique_copy_carray.cpp:6:
/home/scchan/code/build.hcc.vsytch-hcc_installation/compiler/bin/../../include/experimental/algorithm:27:10: fatal error: 'impl/algorithm_impl.inl' file not found
#include "impl/algorithm_impl.inl"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

2017-11-02 01:45 UTC, scchan commented on include/clang/Driver/Options.td
> +  HelpText<"Link to HCC runtime">;
The option description is inconsistent with the option name.
Either we change the description text for `fhcc-bootstrap` to `Use in hcc bootstrap build` or we change this option to some `fno-hcc-lib-link`

2017-11-02 01:45 UTC, scchan commented on include/clang/Driver/Options.td
> +  HelpText<"Don't link to HCC runtime">;
It seems like the HelpText is wrong and should be swapped with the previous option?

We already need a switch for `fno-hcc-bootstrap` ?

2017-11-02 01:45 UTC, scchan commented on lib/Driver/ToolChains/Gnu.h
> +class HCCInstallationDetector;
This class is defined in Hcc.h so this seems to be redundant.

2017-11-02 01:45 UTC, scchan commented on lib/Driver/ToolChains/Gnu.h
> +  friend class HCC::CXXAMPLink;
I believe the reason for this friend class is allow `CXXAMPLink` to call the `ConstructLinkerJob`?  If that's the case, is it really necessary to call `gnutools::Linker::ConstructLinkerJob` from `CXXAMPLink::ConstructJob`?
In other words, could `CXXAMPLink` just return the additional arg back to `gnutools::Linker`  for it to call its own `ConstructLinkerJob`?

2017-11-07 21:15 UTC, whchung commented
@vsytch per discussion please update this PR after reflecting changes suggested by @scchan , and also please submit PRs against `hcc` for required changes in CMake or other components inside `hcc`.

2017-11-08 20:51 UTC, scchan approved these changes
LGTM

2017-11-08 20:51 UTC, merged