Clang is all to eager to opaquely pack records - do not do this for HC.
RadeonOpenCompute/hcc-clang-upgrade pull request #151
Opened 2018-08-23 23:27 UTC by AlexVlx

Clang tries to pack records (opaquely) at the slightest provocation. This is a reasonable optimisation, but it is incredibly troublesome in the context of passing kernel arguments by value through kernarg, since the HLL layout would be based on the `alignof` the unpacked record. The current iteration of the fix is terribly coarse, and is put up to allow early testing and validation (this would touch many things). Subsequent commits will narrow down this behaviour to only apply for the case in which a value of type `T` is passed to a `__global__` function, for all such `T`.

2018-08-24 15:25 UTC, scchan requested changes
Should we move this to near the top of the function before it makes all the alignment calculations since it's a futile exercise in the context of hc?
Is it possible to create a unit test for this?

2018-08-24 15:25 UTC, scchan commented
@yxsamliu please review this since hip-clang may need something similar.

2018-08-24 15:36 UTC, AlexVlx commented
@scchan moving it would just add noise, since you still need to do the bottom vector update. This simplifies merging. Whilst it is undoubtedly possible to devise an unit test, that's not what I'm particularly interested in at the moment. Someone can go and copy & paste the failing sample associated with the original bug, if we want to test it end-to-end, or just generate ISA and check offsets. That can be done subsequently, IMHO.

2018-08-24 15:58 UTC, yxsamliu commented
It seems this will disable pack in any situation for hcc for both host and device code, right?

What if user's code requires it to be packed and uses pragma to force packing. Disabling pack will make the program not working.

Is this issue due to packing, or due to difference between the data layout of the struct of the device and host code? If it is due to the latter, we should find out what causes the difference.

A test case demonstrating this issue would be helpful.

2018-08-24 16:38 UTC, b-sumner commented
Same question here: if hcc supports packed attribute or pragma, then can't this break existing codes?

2018-08-27 02:29 UTC, Jorghi12 commented
Hi all, thanks for investigating this.

I've written a simpler reproduction that you can take a look at.

```
#include "hip/hip_runtime.h"

#define HIP_ASSERT(x) (assert((x)==hipSuccess))

// CUDA kernel argument that defines tensor layout
template <typename T, typename IndexType>
struct TensorInfo {
  TensorInfo(T* p) {
               data = p;
  }

  T* data;
};

// TensorTakeOp Operator
template <typename T, typename IndexType, int Dims>
struct TensorTakeOp {
  TensorTakeOp(TensorInfo<T, IndexType> info, IndexType numel, int64_t*, int64_t*)
    : info(info), numel(numel) {}

  const TensorInfo<T, IndexType> info;
  IndexType numel;
  //int64_t GAINZ;
};

template <typename Op,
          typename Ta, typename Tb,
          typename IndexType,
          int ADims, int BDims>
__global__ void
successful_kernel(Op op, IndexType totalElements) {
  op.info.data[0] = 91;
}

template <typename Op,
          typename Ta, typename Tb,
          typename IndexType,
          int ADims, int BDims>
__global__ void
hanging_kernel(IndexType totalElements, Op op) {
  op.info.data[0] = 91;
}


template <typename T>
void torch_take(T* host_input, T* host_result) {
  /* Reproduction of torch.take()

  Description:
    Given an input list and a list of indicies, output the indicies in the
    provided input list.

  Usage:
    torch.take(input, index)

  Example:
    torch.take([1, 2, 3, 4], [1]) outputs 2.
  */

  // Prepare device side variables
  T* device_input;

  // Compute argument lengths
  int64_t input_length = sizeof(host_input) / sizeof(T);
  int64_t num_indicies = 1;

  // Allocate variables on device
  printf("Allocating memory on device. \n");
  HIP_ASSERT(hipMalloc(&device_input, input_length * sizeof(T)));

  // Copy arguments from host to device
  printf("Copy memory from host to device. \n");
  HIP_ASSERT(hipMemcpy(device_input, host_input, input_length * sizeof(T), hipMemcpyHostToDevice));

  // Prepare the Tensors
  TensorInfo<T, unsigned int> tensor_input = TensorInfo<T, unsigned int>(device_input);

  // Prepare the Operator
  auto tensorTakeOp = TensorTakeOp<T, unsigned int, -2>(tensor_input, input_length, nullptr, nullptr);

  /// Execute the Kernel Launch
  printf("Executing kernel launch. \n");
  hipLaunchKernelGGL(successful_kernel<TensorTakeOp<float, int, -2>, float, long, unsigned int, 1, 1>,
                  512,
                  256,
                  0, 0,
                  tensorTakeOp, num_indicies);

  // Execute the Kernel Launch
  printf("Executing kernel launch. \n");
  hipLaunchKernelGGL(hanging_kernel<TensorTakeOp<float, int, -2>, float, long, unsigned int, 1, 1>,
                  512,
                  256,
                  0, 0,
                  num_indicies, tensorTakeOp);

  // Copy results back to host
  printf("Copying memory from device to host. \n");
  HIP_ASSERT(hipMemcpyAsync(host_result, device_input, num_indicies * sizeof(T), hipMemcpyDeviceToHost));

  // Release device memory
  printf("Freeing memory from device. \n");
  HIP_ASSERT(hipFree(device_input));
}

int main() {
  // Compute the result of torch_take.
  float* host_input = (float*)malloc(sizeof(float)*4);
  float* host_result = (float*)malloc(sizeof(float)*1);

  // Prepare host input values.
  for (int i = 0;i<4;i++){
    host_input[i] = 100 * (4-i);
  }

  // Execute torch_take kernel.
  torch_take<float>(host_input, host_result);

  // Print results.
  for (int i = 0; i < 1; i++) {
    printf("Value at index %d is %f \n", i, host_result[i]);
  }

  return 0;
}


```

2018-08-27 02:40 UTC, Jorghi12 commented
Hi all, thanks for investigating this.

I've provided a much simpler reproduction.
```

#include "hip/hip_runtime.h"

#define HIP_ASSERT(x) (assert((x)==hipSuccess))

// TensorInfo struct that holds the data. (Unnecessary variables emitted)
template <typename T, typename IndexType>
struct TensorInfo {
  TensorInfo(T* p) {
               data = p;
  }

  T* data;
};

// TensorTakeOp Operator
template <typename T, typename IndexType>
struct TensorTakeOp {
  TensorTakeOp(TensorInfo<T, IndexType> info, IndexType numel)
    : info(info), numel(numel) {}

  const TensorInfo<T, IndexType> info;
  IndexType numel;
  //int64_t GAINZ;
};

template <typename Op>
__global__ void
successful_kernel(Op op, unsigned int totalElements) {
  op.info.data[0] = 91;
}

template <typename Op>
__global__ void
hanging_kernel(unsigned int totalElements, Op op) {
  op.info.data[0] = 91;
}


template <typename T>
void torch_take(T* host_input, T* host_result) {
  // Prepare device side variables
  T* device_input;

  // Compute argument lengths
  int64_t input_length = sizeof(host_input) / sizeof(T);
  int64_t num_indicies = 1;

  // Allocate variables on device
  printf("Allocating the input on the device. \n");
  HIP_ASSERT(hipMalloc(&device_input, input_length * sizeof(T)));

  // Copy arguments from host to device
  printf("Copy memory from host to device for the input. \n");
  HIP_ASSERT(hipMemcpy(device_input, host_input, input_length * sizeof(T), hipMemcpyHostToDevice));

  // Prepare the Tensor
  TensorInfo<T, unsigned int> tensor_input = TensorInfo<T, unsigned int>(device_input);

  // Prepare the Operator
  auto tensorTakeOp = TensorTakeOp<T, unsigned int>(tensor_input, input_length);

  // Execute the Kernel Launch
  printf("Executing successful kernel launch. \n");
  hipLaunchKernelGGL(successful_kernel<TensorTakeOp<float, int>>,
                  512,
                  256,
                  0, 0,
                  tensorTakeOp, num_indicies);

  // Execute the Kernel Launch
  printf("Executing hanging kernel launch. \n");
  hipLaunchKernelGGL(hanging_kernel<TensorTakeOp<float, int>>,
                  512,
                  256,
                  0, 0,
                  num_indicies, tensorTakeOp);

  // Copy results back to host
  printf("Copying memory from device to host. \n");
  HIP_ASSERT(hipMemcpyAsync(host_result, device_input, num_indicies * sizeof(T), hipMemcpyDeviceToHost));

  // Release device memory
  printf("Freeing memory from device. \n");
  HIP_ASSERT(hipFree(device_input));
}

int main() {
  // Compute the result of torch_take.
  float* host_input = (float*)malloc(sizeof(float)*4);
  float* host_result = (float*)malloc(sizeof(float)*1);

  // Prepare host input values.
  for (int i = 0;i<4;i++){
    host_input[i] = 100 * (4-i);
  }

  // Execute torch_take kernel.
  torch_take<float>(host_input, host_result);

  // Print the result 
  printf("The result is %f \n", host_result[0]);

  return 0;
}

```

2018-08-31 01:28 UTC, scchan reviewed
LGTM

2018-08-31 01:28 UTC, scchan approved these changes

2018-09-18 15:53 UTC, merged