Add the missing call to isPassedToHIPGlobalFn
RadeonOpenCompute/hcc-clang-upgrade pull request #163
Opened 2018-11-13 20:19 UTC by scchan

which should have been part of an earlier fix for disabling
packing for aggregates passing as kernel args in hcc

2018-11-23 13:31 UTC, AlexVlx commented
Err, I'm not sure that we want this in 2.0 just yet. It may be that with Matt's BE work and the fix I put in in HIP's 731 things just work (practically they should). How about checking that first and iff that is not the case considering this for anything but 1.9.x?

2018-11-23 13:32 UTC, AlexVlx requested changes
See my comment. FWIW I think that HIP-Clang bluntly turning packing off in general is wrong, but that's not quite my concern so I shan't delve into it.

2018-11-23 16:59 UTC, scchan commented
@AlexVlx I created this PR due to discrepancy between 1.9.2.  I haven't been able to validate HIP 731 and  hcc-clang-upgrade 161 since some PT CUDA tests regressed when ported to 1.9.2.  Also, branch for 2.0 will be created soon, could you work with Matt and make an assessment whether we need this? Thx

2018-11-23 17:08 UTC, AlexVlx commented
@scchan but this is not against 1.9.x but rather against master, so I don't understand what "discrepancy between 1.9.2" means here - if merged this'd be hoovered into 2.0, I believe. Since the only consumer of the workaround is PT, unless that is in a functional state on 2.0 there's no back-of-the-envelope assessment to be had here. We will have to coordinate with the pyTorch team after TG to start looking at that.

2018-11-23 17:21 UTC, scchan commented
@AlexVlx I meant 1.9.2 has this but clang_tot_upgrade doesn't.  I thought it was an oversight and didn't know it was left out intentionally(?)

2018-11-23 17:26 UTC, AlexVlx commented
Yes, it is intentionally left out from 2.0.

2018-11-28 21:25 UTC, scchan commented
@AlexVlx As discussed, we want to enable this packing fix for now until we find a solution to the metadata issue in the HIP runtime?

2018-11-28 21:27 UTC, AlexVlx approved these changes

2018-11-29 16:07 UTC, merged