Fix FCS HCC Unit tests failures
RadeonOpenCompute/hcc-clang-upgrade pull request #173
Opened 2019-03-18 19:02 UTC by aaronenyeshi

This fixes many of the HCC Unit tests with FCS enabled. From 154 failures to 5 failures.

2019-03-18 19:12 UTC, AlexVlx requested changes
It may well be that it fixes something, but this is semantically incorrect (a barrier must be "seen" and arrived at by all lanes). I forget the discussion around this, but a barrier needs to carry at least the `convergent` attribute... IIRC `noduplicate` is somewhat excessive. @arsenm is probably a better source here. I'm surprised that the barrier wrapper itself would have any interaction with FCS though...
Follow-up: we shouldn't be setting this in the FE, but rather insider the RT itself.

2019-03-18 19:22 UTC, arsenm commented
This is incorrect. NoDuplicate was entirely a mistake to introduce. It's both too strong, and insufficiently strong for what barrier needs.

Is HCC correctly marking *all* functions with convergent? This is necessary, and what is done for OpenCL and CUDA. It's one of those language checks which might not have been updated

2019-03-18 19:37 UTC, aaronenyeshi commented
It looks like the declaration already switched to convergent attribute:
https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/include/hc_defines.h#L54

2019-03-18 19:41 UTC, scchan commented
The NoDuplicate was added to workaround some code motion related bugs when hcc was still using the hsail backend (I think).  It should be removed.

2019-03-18 19:41 UTC, aaronenyeshi commented
Also, I've tested this removal of NoDuplicate, and all HCC Unit tests passing without FCS enabled. And 5 Unit tests failing with FCS enabled.

2019-03-18 19:45 UTC, arsenm commented
The explicit attribute on the declaration is purely redundant. All functions/declarations need to be assumed convergent at the beginning

2019-03-18 21:11 UTC, aaronenyeshi commented
This change was added 3 years ago: https://github.com/RadeonOpenCompute/hcc-clang-upgrade/commit/c692de58257d90922b9bef12aada2f70a47c49cd. We should remove this attribute `noduplicate`. Also I wonder why we avoid loop vectorization back then

2019-03-19 15:03 UTC, scchan commented
@aaronenyeshi  could you address the issue raised by @arsenm ?
@arsenm I presume you are referring to `assumeFunctionsAreConvergent()` that needs to be fixed?

2019-03-19 15:05 UTC, arsenm commented
> @aaronenyeshi could you address the issue raised by @arsenm ?
> @arsenm I presume you are referring to `assumeFunctionsAreConvergent()` that needs to be fixed?

Yes

2019-03-19 17:44 UTC, scchan requested changes
- removed special handling for `amp_barrier`
- mark all device functions as convergent as suggested by Matt

2019-03-19 17:44 UTC, scchan commented on lib/CodeGen/CodeGenModule.cpp
>            F->addFnAttr(llvm::Attribute::NoUnwind);
NoUnwind is probably not needed here as well so let's remove the specialization for `amp_barrier` altogther

2019-03-19 18:17 UTC, aaronenyeshi commented
> > @aaronenyeshi could you address the issue raised by @arsenm ?
> > @arsenm I presume you are referring to `assumeFunctionsAreConvergent()` that needs to be fixed?
> 
> Yes

Strangly, AMPIsDevice is a CodeGenOpt and CPlusPlusAMP is a LangOpt. For CUDA, both CUDA and CUDAIsDevice are LangOpts. Should I change `assumeFunctionsAreConvergent` to only check for CPlusPlusAMP? since its scope only sees LangOpts

2019-03-19 18:24 UTC, scchan commented
Can't we use `DevicePath`?

2019-03-19 18:49 UTC, aaronenyeshi commented
> Can't we use `DevicePath`?

Good idea, I didn't know that was an option. The name sounds generic, also its not upstream. I will use it instead

2019-03-19 19:57 UTC, aaronenyeshi commented
@scchan  @arsenm I've committed the changes you've requested. It doesn't cause any regression to regular HCC unit tests w/o FCS. For FCS enabled, it shows the same improvement (ie. 154 failures to 5 failures).

2019-03-19 19:57 UTC, AlexVlx approved these changes

2019-03-19 20:21 UTC, scchan approved these changes
LGTM

2019-03-19 20:21 UTC, merged